org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

archives_base_name=localcapes
mod_id=localcapes
mod_name=LocalCapes
mod_version=1.6.0
maven_group=dev.localcapes
mod_author=JinRui_MaoMao
mod_description=Client-side custom Minecraft capes loaded from local PNG files.
mod_license=MIT

architectury_version=13.0.11

fabric_loader_version=0.16.14
fabric_api_version=0.116.17+1.21.1

neoforge_version=21.1.256
